health_fitness/Models/ErrorViewModel.cs
namespace health_fitness.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

health_fitness/Models/StepInfo.cs
using System.ComponentModel.DataAnnotations;

namespace health_fitness.Models
{
	public class StepInfo
	{
        public int stepsnumber { get; set; }
        [Key]
        public DateTime time { get; set; }
    }
}

health_fitness/Models/stepscontext.cs
using Microsoft.EntityFrameworkCore;

namespace health_fitness.Models

{
    public class stepscontext:DbContext
    {
        public stepscontext(DbContextOptions<stepscontext> options)
            :base(options)
        {

        }
        //اسم المودل بالمفرد داخل الحاصرات وبالجمع بعدها
        public DbSet<StepInfo> StepSInfo { get; set; }
    }
}

health_fitness/Controllers/HomeController.cs
using health_fitness.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace health_fitness.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

health_fitness/Controllers/PedometerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using health_fitness.Models;

namespace health_fitness.Controllers
{
    public class PedometerController : Controller
    {
        private stepscontext _stContext;
        public PedometerController(stepscontext stContext)
        {
            _stContext = stContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Steps()
        {
            return View();
        }
        [HttpPost]
        public IActionResult StepsToCalories(StepInfo NumOfSteps)
        {
            NumOfSteps.time = DateTime.Now;
            
            double TotalCaloriesBurned = NumOfSteps.stepsnumber * 0.04;
            _stContext.StepSInfo.Add(NumOfSteps);
            _stContext.SaveChanges ();
            return View(TotalCaloriesBurned);
        }
    }
}

health_fitness/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Yaaa Welcome</h1>
    <br />
    <p>To Calculate your calories Click The button...</p><br />
    <a asp-controller="Pedometer" asp-action="Steps" style = "text-decoration:none;font-size:20px;background-color:lightgreen;color:white;padding:20px;">To The Page</a>
</div>

health_fitness/Views/Pedometer/Steps.cshtml
@{
    ViewData["Title"] = "Enter Steps";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Pedometer" asp-action="StepsToCalories" method="post">
    <p>To Calculate your Calories Burned Enter your steps that you took <br /> and click on the Green button </p>
    <div>
        <input type="number" name="stepsnumber" placeholder="Your Steps" style="width:200px;height:40px;text-align:center;font-size:20px;"/>
    </div>
    <br />
        <button type="submit" class="btn btn-success btn-lg">Calculate Calories Burned</button>

</form>

health_fitness/Views/Pedometer/StepsToCalories.cshtml
@model double

<h2>Total Calories Burned</h2>
<p>You burned @Model calories</p><br />
<a asp-controller="Pedometer" asp-action="Steps" style = "text-decoration:none;font-size:20px;background-color:lightgreen;color:white;padding:20px;">Back</a>

health_fitness/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - health_fitness</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/health_fitness.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">health_fitness</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>